-- PixelRP: the Exterior Modern set, in Builders > Customs.
--
-- 33 exterior pieces - blocks, fences, hedges, half walls, paving and
-- windows - hung under the EXISTING Customs category rather than making a new
-- top-level one, the same way Bsstonino is. Generated by
-- docker/nitro/import-pack-tree.py.
--
-- The pack arrived already converted except for Whitesparring.swf, which went
-- through nitro-converter (yarn start:convert-swf) before being folded in with
-- the rest.
--
-- The rendering half is the .nitro bundles, the icons and the FurnitureData
-- entries under nitro/overrides/; the rows below are inert without them.
--
-- Everything is free - the catalog has been since 90_FreeCatalog.
--
-- Idempotent: fixed id ranges, cleared before insert. The sets under Customs are
-- renumbered alphabetically at the end, which lands the same way every run.

SET @builders := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = -1 AND `caption` = 'Builders' LIMIT 1),
    912362);
SET @customs := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `id` = 944000 LIMIT 1),
    (SELECT `id` FROM `catalog_pages` WHERE `caption` = 'Customs' AND `parent_id` = @builders
        ORDER BY `id` LIMIT 1));

DELETE FROM `catalog_items` WHERE `item_id` BETWEEN 109900 AND 109932;
DELETE FROM `catalog_pages` WHERE `id` BETWEEN 947000 AND 947999;
DELETE FROM `furniture` WHERE `id` BETWEEN 109900 AND 109932;

INSERT INTO `catalog_pages`
    (`id`,`parent_id`,`caption`,`icon_image`,`min_rank`,`min_vip`,`order_num`,`page_link`,
     `page_layout`,`page_strings_1`,`page_strings_2`,`visible`,`enabled`)
VALUES
    (947000, @customs, 'Exterior Modern', 193, 2, 0, 1, '', 'default_3x3', '', '', b'1', b'1');

-- Furniture. id == sprite_id, the convention every custom line here follows;
-- interaction_modes_count is the bundle's own animation count.
INSERT INTO `furniture` (`id`,`item_name`,`public_name`,`type`,`width`,`length`,`stack_height`,`can_stack`,`can_sit`,`is_walkable`,`sprite_id`,`allow_recycle`,`allow_trade`,`allow_marketplace_sell`,`allow_gift`,`allow_inventory_stack`,`interaction_type`,`behaviour_data`,`interaction_modes_count`,`is_rare`) VALUES
    (109900,'Whitesparring','Whitesparring','s',2,2,1.0,'1','0','0',109900,'0','1','0','1','1','default',0,1,'0'),
    (109901,'archi_23_block_01','Archi 23 Block 01','s',1,1,1.0,'1','0','0',109901,'0','1','0','1','1','default',0,8,'0'),
    (109902,'archi_23_block_03_01','Archi 23 Block 03 01','s',1,1,1.0,'1','0','0',109902,'0','1','0','1','1','default',0,12,'0'),
    (109903,'archi_23_concrete_bench_01','Archi 23 Concrete Bench 01','s',2,1,1.2,'1','1','0',109903,'0','1','0','1','1','default',0,10,'0'),
    (109904,'archi_23_door_01','Archi 23 Door 01','s',2,1,1.0,'1','0','0',109904,'0','1','0','1','1','default',0,12,'0'),
    (109905,'archi_23_door_01_01','Archi 23 Door 01 01','s',1,1,1.0,'1','0','0',109905,'0','1','0','1','1','default',0,12,'0'),
    (109906,'archi_23_fence_01','Archi 23 Fence 01','s',1,1,1.0,'1','0','0',109906,'0','1','0','1','1','default',0,10,'0'),
    (109907,'archi_23_floor_01','Archi 23 Floor 01','s',2,2,1.0,'1','0','0',109907,'0','1','0','1','1','default',0,3,'0'),
    (109908,'archi_23_floor_tile_01','Archi 23 Floor Tile 01','s',1,1,1.0,'1','0','0',109908,'0','1','0','1','1','default',0,3,'0'),
    (109909,'archi_23_grass_patch_floor_01','Archi 23 Grass Patch Floor 01','s',2,2,1.0,'1','0','0',109909,'0','1','0','1','1','default',0,3,'0'),
    (109910,'archi_23_grass_patch_tile_01','Archi 23 Grass Patch Tile 01','s',1,1,1.0,'1','0','0',109910,'0','1','0','1','1','default',0,3,'0'),
    (109911,'archi_23_half_pillar_01_01','Archi 23 Half Pillar 01 01','s',1,1,1.0,'1','0','0',109911,'0','1','0','1','1','default',0,16,'0'),
    (109912,'archi_23_half_wall_01_01','Archi 23 Half Wall 01 01','s',1,1,1.0,'1','0','0',109912,'0','1','0','1','1','default',0,8,'0'),
    (109913,'archi_23_half_wall_02_01','Archi 23 Half Wall 02 01','s',1,1,1.0,'1','0','0',109913,'0','1','0','1','1','default',0,12,'0'),
    (109914,'archi_23_half_wall_corner_0101','Archi 23 Half Wall Corner 0101','s',1,1,1.0,'1','0','0',109914,'0','1','0','1','1','default',0,8,'0'),
    (109915,'archi_23_half_wall_corner_0201','Archi 23 Half Wall Corner 0201','s',1,1,1.0,'1','0','0',109915,'0','1','0','1','1','default',0,12,'0'),
    (109916,'archi_23_hedge_01','Archi 23 Hedge 01','s',2,1,1.0,'1','0','0',109916,'0','1','0','1','1','default',0,6,'0'),
    (109917,'archi_23_hedge_01_01','Archi 23 Hedge 01 01','s',1,1,1.0,'1','0','0',109917,'0','1','0','1','1','default',0,6,'0'),
    (109918,'archi_23_pebbles_floor_01','Archi 23 Pebbles Floor 01','s',2,2,1.0,'1','0','0',109918,'0','1','0','1','1','default',0,2,'0'),
    (109919,'archi_23_pebbles_tile_01','Archi 23 Pebbles Tile 01','s',1,1,1.0,'1','0','0',109919,'0','1','0','1','1','default',0,2,'0'),
    (109920,'archi_23_steel_column_01','Archi 23 Steel Column 01','s',1,1,1.0,'1','0','0',109920,'0','1','0','1','1','default',0,12,'0'),
    (109921,'archi_23_steel_fence_01','Archi 23 Steel Fence 01','s',2,1,1.0,'1','0','0',109921,'0','1','0','1','1','default',0,4,'0'),
    (109922,'archi_23_steel_fence_01_01','Archi 23 Steel Fence 01 01','s',2,1,1.0,'1','0','0',109922,'0','1','0','1','1','default',0,4,'0'),
    (109923,'archi_23_steel_fence_02_01','Archi 23 Steel Fence 02 01','s',1,1,1.0,'1','0','0',109923,'0','1','0','1','1','default',0,4,'0'),
    (109924,'archi_23_steel_gate_01','Archi 23 Steel Gate 01','s',2,1,1.0,'1','0','0',109924,'0','1','0','1','1','default',0,2,'0'),
    (109925,'archi_23_steel_gate_01_01','Archi 23 Steel Gate 01 01','s',1,1,1.0,'1','0','0',109925,'0','1','0','1','1','default',0,2,'0'),
    (109926,'archi_23_window_01','Archi 23 Window 01','s',2,1,1.0,'1','0','0',109926,'0','1','0','1','1','default',0,6,'0'),
    (109927,'archi_23_window_01_01','Archi 23 Window 01 01','s',2,1,1.0,'1','0','0',109927,'0','1','0','1','1','default',0,6,'0'),
    (109928,'archi_23_window_02_01','Archi 23 Window 02 01','s',1,1,1.0,'1','0','0',109928,'0','1','0','1','1','default',0,6,'0'),
    (109929,'archi_23_window_03_01','Archi 23 Window 03 01','s',1,1,1.0,'1','0','0',109929,'0','1','0','1','1','default',0,6,'0'),
    (109930,'archi_23_wsb_01','Archi 23 Wsb 01','s',1,1,1.0,'1','0','0',109930,'0','1','0','1','1','default',0,12,'0'),
    (109931,'archi_23_wsc_01','Archi 23 Wsc 01','s',1,1,1.0,'1','0','0',109931,'0','1','0','1','1','default',0,6,'0'),
    (109932,'archi_23_wss_01','Archi 23 Wss 01','s',1,1,1.0,'1','0','0',109932,'0','1','0','1','1','default',0,6,'0');

INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`) VALUES
    (947000,'109900','Whitesparring',0,0,0,1,0,0,'1','','',-1),
    (947000,'109901','Archi 23 Block 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109902','Archi 23 Block 03 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109903','Archi 23 Concrete Bench 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109904','Archi 23 Door 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109905','Archi 23 Door 01 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109906','Archi 23 Fence 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109907','Archi 23 Floor 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109908','Archi 23 Floor Tile 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109909','Archi 23 Grass Patch Floor 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109910','Archi 23 Grass Patch Tile 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109911','Archi 23 Half Pillar 01 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109912','Archi 23 Half Wall 01 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109913','Archi 23 Half Wall 02 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109914','Archi 23 Half Wall Corner 0101',0,0,0,1,0,0,'1','','',-1),
    (947000,'109915','Archi 23 Half Wall Corner 0201',0,0,0,1,0,0,'1','','',-1),
    (947000,'109916','Archi 23 Hedge 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109917','Archi 23 Hedge 01 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109918','Archi 23 Pebbles Floor 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109919','Archi 23 Pebbles Tile 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109920','Archi 23 Steel Column 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109921','Archi 23 Steel Fence 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109922','Archi 23 Steel Fence 01 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109923','Archi 23 Steel Fence 02 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109924','Archi 23 Steel Gate 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109925','Archi 23 Steel Gate 01 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109926','Archi 23 Window 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109927','Archi 23 Window 01 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109928','Archi 23 Window 02 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109929','Archi 23 Window 03 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109930','Archi 23 Wsb 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109931','Archi 23 Wsc 01',0,0,0,1,0,0,'1','','',-1),
    (947000,'109932','Archi 23 Wss 01',0,0,0,1,0,0,'1','','',-1);

SET @n := 0;
UPDATE `catalog_pages` SET `order_num` = (@n := @n + 1)
    WHERE `parent_id` = @customs
    ORDER BY `caption`;

-- ---------------------------------------------------------------------------
-- Hand-added after the generator ran, and NOT something import-pack-tree.py
-- will reproduce: re-running the import would emit the rows above without this
-- block, so it lives here as an UPDATE keyed by name rather than as edits to
-- the INSERT.
--
-- The six ground pieces come out of their bundles declaring z = 1.0 and no
-- walkability, which is what the pack really says - Habbo furni routinely
-- declares 1.0 and leaves standing to the furnidata flag the importer cannot
-- see. Imported faithfully, a paved patio is six blocking tiles a builder
-- cannot stand on, which is not what anybody laying paving means.
--
-- So they get the Function tool's own 'rug' preset: walkable, stackable, flat.
-- Named individually rather than matched on LIKE '%floor%' - 'archi_23_door_01'
-- is not a floor, and a pattern that catches it would be a silent trap.
UPDATE `furniture`
    SET `is_walkable` = '1', `stack_height` = 0, `can_stack` = '1'
    WHERE `item_name` IN (
        'archi_23_floor_01',
        'archi_23_floor_tile_01',
        'archi_23_grass_patch_floor_01',
        'archi_23_grass_patch_tile_01',
        'archi_23_pebbles_floor_01',
        'archi_23_pebbles_tile_01');

-- Should read six rows, all walkable at height 0.
SELECT `item_name`, `is_walkable`, `stack_height`, `can_stack`
    FROM `furniture`
    WHERE `item_name` LIKE 'archi\_23\_%'
      AND (`is_walkable` = '1' OR `stack_height` = 0)
    ORDER BY `item_name`;
