-- PixelRP: the Modern Hospital set, in Builders > Corporations > Hospital.
--
-- 60 pieces on ONE page under the existing Corporations category, beside
-- the Corporation Gate 146 put there. Generated by
-- docker/nitro/import-pack-tree.py.
--
-- A flat page rather than subcategories because the download is flat: sixty
-- bundles of one set, with nothing in it that groups them.
--
-- The pack carries no names - its manifest records each item's classname and
-- nothing else - so the titles are the set's own name and the number the
-- bundle already had: 'Modern Hospital 01' through 60. Derived, not invented;
-- there is nothing in the download that says which one is the bed.
--
-- The rendering half is the .nitro bundles, the icons and the FurnitureData
-- entries under nitro/overrides/; the rows below are inert without them.
--
-- Everything is free - the catalog has been since 90_FreeCatalog.
--
-- Idempotent: fixed id ranges, cleared before insert. Hospital is the only page in its range.

SET @builders := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = -1 AND `caption` = 'Builders' LIMIT 1),
    912362);
SET @corps := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = @builders AND `caption` = 'Corporations' LIMIT 1),
    @builders);

DELETE FROM `catalog_items` WHERE `item_id` BETWEEN 110400 AND 110459;
DELETE FROM `catalog_pages` WHERE `id` BETWEEN 950000 AND 950999;
DELETE FROM `furniture` WHERE `id` BETWEEN 110400 AND 110459;

INSERT INTO `catalog_pages`
    (`id`,`parent_id`,`caption`,`icon_image`,`min_rank`,`min_vip`,`order_num`,`page_link`,
     `page_layout`,`page_strings_1`,`page_strings_2`,`visible`,`enabled`)
VALUES
    (950000, @corps, 'Hospital', 193, 2, 0, 1, '', 'default_3x3', '', '', b'1', b'1');


-- Furniture. id == sprite_id, the convention every custom line here follows;
-- interaction_modes_count is the bundle's own animation count.
INSERT INTO `furniture` (`id`,`item_name`,`public_name`,`type`,`width`,`length`,`stack_height`,`can_stack`,`can_sit`,`is_walkable`,`sprite_id`,`allow_recycle`,`allow_trade`,`allow_marketplace_sell`,`allow_gift`,`allow_inventory_stack`,`interaction_type`,`behaviour_data`,`interaction_modes_count`,`is_rare`) VALUES
    (110400,'Hellsinore_HospitalModerno_01','Modern Hospital 01','s',1,1,1.0,'1','0','0',110400,'0','1','0','1','1','default',0,3,'0'),
    (110401,'Hellsinore_HospitalModerno_02','Modern Hospital 02','s',4,2,1.0,'1','0','0',110401,'0','1','0','1','1','default',0,2,'0'),
    (110402,'Hellsinore_HospitalModerno_03','Modern Hospital 03','s',1,1,1.0,'1','0','0',110402,'0','1','0','1','1','default',0,16,'0'),
    (110403,'Hellsinore_HospitalModerno_04','Modern Hospital 04','s',1,1,1.0,'1','0','0',110403,'0','1','0','1','1','default',0,16,'0'),
    (110404,'Hellsinore_HospitalModerno_05','Modern Hospital 05','s',2,1,1.0,'1','0','0',110404,'0','1','0','1','1','default',0,4,'0'),
    (110405,'Hellsinore_HospitalModerno_06','Modern Hospital 06','s',1,1,1.0,'1','0','0',110405,'0','1','0','1','1','default',0,5,'0'),
    (110406,'Hellsinore_HospitalModerno_07','Modern Hospital 07','s',1,1,1.0,'1','0','0',110406,'0','1','0','1','1','default',0,5,'0'),
    (110407,'Hellsinore_HospitalModerno_08','Modern Hospital 08','s',1,1,1.0,'1','0','0',110407,'0','1','0','1','1','default',0,1,'0'),
    (110408,'Hellsinore_HospitalModerno_09','Modern Hospital 09','s',1,1,1.0,'1','0','0',110408,'0','1','0','1','1','default',0,15,'0'),
    (110409,'Hellsinore_HospitalModerno_10','Modern Hospital 10','s',1,1,1.0,'1','0','0',110409,'0','1','0','1','1','default',0,1,'0'),
    (110410,'Hellsinore_HospitalModerno_11','Modern Hospital 11','s',1,1,1.0,'1','0','0',110410,'0','1','0','1','1','default',0,4,'0'),
    (110411,'Hellsinore_HospitalModerno_12','Modern Hospital 12','s',1,1,1.0,'1','0','0',110411,'0','1','0','1','1','default',0,1,'0'),
    (110412,'Hellsinore_HospitalModerno_13','Modern Hospital 13','s',1,1,1.0,'1','0','0',110412,'0','1','0','1','1','default',0,1,'0'),
    (110413,'Hellsinore_HospitalModerno_14','Modern Hospital 14','s',1,1,1.0,'1','0','0',110413,'0','1','0','1','1','default',0,2,'0'),
    (110414,'Hellsinore_HospitalModerno_15','Modern Hospital 15','s',1,1,1.0,'1','0','0',110414,'0','1','0','1','1','default',0,1,'0'),
    (110415,'Hellsinore_HospitalModerno_16','Modern Hospital 16','s',1,1,1.0,'1','0','0',110415,'0','1','0','1','1','default',0,1,'0'),
    (110416,'Hellsinore_HospitalModerno_17','Modern Hospital 17','s',1,1,1.0,'1','0','0',110416,'0','1','0','1','1','default',0,3,'0'),
    (110417,'Hellsinore_HospitalModerno_18','Modern Hospital 18','s',1,1,1.0,'1','0','0',110417,'0','1','0','1','1','default',0,12,'0'),
    (110418,'Hellsinore_HospitalModerno_19','Modern Hospital 19','s',1,1,1.0,'1','0','0',110418,'0','1','0','1','1','default',0,6,'0'),
    (110419,'Hellsinore_HospitalModerno_20','Modern Hospital 20','s',1,1,1.0,'1','0','0',110419,'0','1','0','1','1','default',0,2,'0'),
    (110420,'Hellsinore_HospitalModerno_21','Modern Hospital 21','s',1,1,1.0,'1','0','0',110420,'0','1','0','1','1','default',0,6,'0'),
    (110421,'Hellsinore_HospitalModerno_22','Modern Hospital 22','s',1,1,1.0,'1','0','0',110421,'0','1','0','1','1','default',0,3,'0'),
    (110422,'Hellsinore_HospitalModerno_23','Modern Hospital 23','s',2,1,1.0,'1','0','0',110422,'0','1','0','1','1','default',0,3,'0'),
    (110423,'Hellsinore_HospitalModerno_24','Modern Hospital 24','s',1,1,1.0,'1','0','0',110423,'0','1','0','1','1','default',0,3,'0'),
    (110424,'Hellsinore_HospitalModerno_25','Modern Hospital 25','s',1,1,1.0,'1','0','0',110424,'0','1','0','1','1','default',0,3,'0'),
    (110425,'Hellsinore_HospitalModerno_26','Modern Hospital 26','s',1,1,1.0,'1','0','0',110425,'0','1','0','1','1','default',0,15,'0'),
    (110426,'Hellsinore_HospitalModerno_27','Modern Hospital 27','s',1,1,1.0,'1','0','0',110426,'0','1','0','1','1','default',0,1,'0'),
    (110427,'Hellsinore_HospitalModerno_28','Modern Hospital 28','s',1,1,1.0,'1','0','0',110427,'0','1','0','1','1','default',0,2,'0'),
    (110428,'Hellsinore_HospitalModerno_29','Modern Hospital 29','s',1,1,1.0,'1','0','0',110428,'0','1','0','1','1','default',0,4,'0'),
    (110429,'Hellsinore_HospitalModerno_30','Modern Hospital 30','s',1,1,1.0,'1','0','0',110429,'0','1','0','1','1','default',0,2,'0'),
    (110430,'Hellsinore_HospitalModerno_31','Modern Hospital 31','s',1,1,1.0,'1','0','0',110430,'0','1','0','1','1','default',0,4,'0'),
    (110431,'Hellsinore_HospitalModerno_32','Modern Hospital 32','s',1,1,1.0,'1','0','0',110431,'0','1','0','1','1','default',0,6,'0'),
    (110432,'Hellsinore_HospitalModerno_33','Modern Hospital 33','s',1,3,1.0,'1','0','0',110432,'0','1','0','1','1','default',0,2,'0'),
    (110433,'Hellsinore_HospitalModerno_34','Modern Hospital 34','s',3,1,1.0,'1','0','0',110433,'0','1','0','1','1','default',0,3,'0'),
    (110434,'Hellsinore_HospitalModerno_35','Modern Hospital 35','s',1,1,1.0,'1','0','0',110434,'0','1','0','1','1','default',0,2,'0'),
    (110435,'Hellsinore_HospitalModerno_36','Modern Hospital 36','s',1,3,1.0,'1','0','0',110435,'0','1','0','1','1','default',0,3,'0'),
    (110436,'Hellsinore_HospitalModerno_37','Modern Hospital 37','s',1,1,1.0,'1','0','0',110436,'0','1','0','1','1','default',0,6,'0'),
    (110437,'Hellsinore_HospitalModerno_38','Modern Hospital 38','s',1,1,1.0,'1','0','0',110437,'0','1','0','1','1','default',0,3,'0'),
    (110438,'Hellsinore_HospitalModerno_39','Modern Hospital 39','s',1,1,1.0,'1','0','0',110438,'0','1','0','1','1','default',0,12,'0'),
    (110439,'Hellsinore_HospitalModerno_40','Modern Hospital 40','s',1,1,1.0,'1','0','0',110439,'0','1','0','1','1','default',0,1,'0'),
    (110440,'Hellsinore_HospitalModerno_41','Modern Hospital 41','s',3,1,1.0,'1','0','0',110440,'0','1','0','1','1','default',0,3,'0'),
    (110441,'Hellsinore_HospitalModerno_42','Modern Hospital 42','s',2,1,1.0,'1','0','0',110441,'0','1','0','1','1','default',0,8,'0'),
    (110442,'Hellsinore_HospitalModerno_43','Modern Hospital 43','s',1,1,1.0,'1','0','0',110442,'0','1','0','1','1','default',0,4,'0'),
    (110443,'Hellsinore_HospitalModerno_44','Modern Hospital 44','s',2,1,1.0,'1','0','0',110443,'0','1','0','1','1','default',0,2,'0'),
    (110444,'Hellsinore_HospitalModerno_45','Modern Hospital 45','s',2,1,1.0,'1','0','0',110444,'0','1','0','1','1','default',0,2,'0'),
    (110445,'Hellsinore_HospitalModerno_46','Modern Hospital 46','s',2,1,1.0,'1','0','0',110445,'0','1','0','1','1','default',0,2,'0'),
    (110446,'Hellsinore_HospitalModerno_47','Modern Hospital 47','s',2,1,1.0,'1','0','0',110446,'0','1','0','1','1','default',0,2,'0'),
    (110447,'Hellsinore_HospitalModerno_48','Modern Hospital 48','s',2,1,1.0,'1','0','0',110447,'0','1','0','1','1','default',0,2,'0'),
    (110448,'Hellsinore_HospitalModerno_49','Modern Hospital 49','s',2,1,1.0,'1','0','0',110448,'0','1','0','1','1','default',0,6,'0'),
    (110449,'Hellsinore_HospitalModerno_50','Modern Hospital 50','s',1,1,1.0,'1','0','0',110449,'0','1','0','1','1','default',0,3,'0'),
    (110450,'Hellsinore_HospitalModerno_51','Modern Hospital 51','s',1,1,1.0,'1','0','0',110450,'0','1','0','1','1','default',0,4,'0'),
    (110451,'Hellsinore_HospitalModerno_52','Modern Hospital 52','s',1,1,1.0,'1','0','0',110451,'0','1','0','1','1','default',0,2,'0'),
    (110452,'Hellsinore_HospitalModerno_53','Modern Hospital 53','s',1,1,1.0,'1','0','0',110452,'0','1','0','1','1','default',0,11,'0'),
    (110453,'Hellsinore_HospitalModerno_54','Modern Hospital 54','s',1,1,1.0,'1','0','0',110453,'0','1','0','1','1','default',0,3,'0'),
    (110454,'Hellsinore_HospitalModerno_55','Modern Hospital 55','s',1,1,1.0,'1','0','0',110454,'0','1','0','1','1','default',0,6,'0'),
    (110455,'Hellsinore_HospitalModerno_56','Modern Hospital 56','s',1,1,1.0,'1','0','0',110455,'0','1','0','1','1','default',0,6,'0'),
    (110456,'Hellsinore_HospitalModerno_57','Modern Hospital 57','s',1,1,1.0,'1','0','0',110456,'0','1','0','1','1','default',0,16,'0'),
    (110457,'Hellsinore_HospitalModerno_58','Modern Hospital 58','s',1,1,1.0,'1','0','0',110457,'0','1','0','1','1','default',0,8,'0'),
    (110458,'Hellsinore_HospitalModerno_59','Modern Hospital 59','s',2,1,1.0,'1','0','0',110458,'0','1','0','1','1','default',0,3,'0'),
    (110459,'Hellsinore_HospitalModerno_60','Modern Hospital 60','s',1,1,1.0,'1','0','0',110459,'0','1','0','1','1','default',0,3,'0');

INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`) VALUES
    (950000,'110400','Modern Hospital 01',0,0,0,1,0,0,'1','','',-1),
    (950000,'110401','Modern Hospital 02',0,0,0,1,0,0,'1','','',-1),
    (950000,'110402','Modern Hospital 03',0,0,0,1,0,0,'1','','',-1),
    (950000,'110403','Modern Hospital 04',0,0,0,1,0,0,'1','','',-1),
    (950000,'110404','Modern Hospital 05',0,0,0,1,0,0,'1','','',-1),
    (950000,'110405','Modern Hospital 06',0,0,0,1,0,0,'1','','',-1),
    (950000,'110406','Modern Hospital 07',0,0,0,1,0,0,'1','','',-1),
    (950000,'110407','Modern Hospital 08',0,0,0,1,0,0,'1','','',-1),
    (950000,'110408','Modern Hospital 09',0,0,0,1,0,0,'1','','',-1),
    (950000,'110409','Modern Hospital 10',0,0,0,1,0,0,'1','','',-1),
    (950000,'110410','Modern Hospital 11',0,0,0,1,0,0,'1','','',-1),
    (950000,'110411','Modern Hospital 12',0,0,0,1,0,0,'1','','',-1),
    (950000,'110412','Modern Hospital 13',0,0,0,1,0,0,'1','','',-1),
    (950000,'110413','Modern Hospital 14',0,0,0,1,0,0,'1','','',-1),
    (950000,'110414','Modern Hospital 15',0,0,0,1,0,0,'1','','',-1),
    (950000,'110415','Modern Hospital 16',0,0,0,1,0,0,'1','','',-1),
    (950000,'110416','Modern Hospital 17',0,0,0,1,0,0,'1','','',-1),
    (950000,'110417','Modern Hospital 18',0,0,0,1,0,0,'1','','',-1),
    (950000,'110418','Modern Hospital 19',0,0,0,1,0,0,'1','','',-1),
    (950000,'110419','Modern Hospital 20',0,0,0,1,0,0,'1','','',-1),
    (950000,'110420','Modern Hospital 21',0,0,0,1,0,0,'1','','',-1),
    (950000,'110421','Modern Hospital 22',0,0,0,1,0,0,'1','','',-1),
    (950000,'110422','Modern Hospital 23',0,0,0,1,0,0,'1','','',-1),
    (950000,'110423','Modern Hospital 24',0,0,0,1,0,0,'1','','',-1),
    (950000,'110424','Modern Hospital 25',0,0,0,1,0,0,'1','','',-1),
    (950000,'110425','Modern Hospital 26',0,0,0,1,0,0,'1','','',-1),
    (950000,'110426','Modern Hospital 27',0,0,0,1,0,0,'1','','',-1),
    (950000,'110427','Modern Hospital 28',0,0,0,1,0,0,'1','','',-1),
    (950000,'110428','Modern Hospital 29',0,0,0,1,0,0,'1','','',-1),
    (950000,'110429','Modern Hospital 30',0,0,0,1,0,0,'1','','',-1),
    (950000,'110430','Modern Hospital 31',0,0,0,1,0,0,'1','','',-1),
    (950000,'110431','Modern Hospital 32',0,0,0,1,0,0,'1','','',-1),
    (950000,'110432','Modern Hospital 33',0,0,0,1,0,0,'1','','',-1),
    (950000,'110433','Modern Hospital 34',0,0,0,1,0,0,'1','','',-1),
    (950000,'110434','Modern Hospital 35',0,0,0,1,0,0,'1','','',-1),
    (950000,'110435','Modern Hospital 36',0,0,0,1,0,0,'1','','',-1),
    (950000,'110436','Modern Hospital 37',0,0,0,1,0,0,'1','','',-1),
    (950000,'110437','Modern Hospital 38',0,0,0,1,0,0,'1','','',-1),
    (950000,'110438','Modern Hospital 39',0,0,0,1,0,0,'1','','',-1),
    (950000,'110439','Modern Hospital 40',0,0,0,1,0,0,'1','','',-1),
    (950000,'110440','Modern Hospital 41',0,0,0,1,0,0,'1','','',-1),
    (950000,'110441','Modern Hospital 42',0,0,0,1,0,0,'1','','',-1),
    (950000,'110442','Modern Hospital 43',0,0,0,1,0,0,'1','','',-1),
    (950000,'110443','Modern Hospital 44',0,0,0,1,0,0,'1','','',-1),
    (950000,'110444','Modern Hospital 45',0,0,0,1,0,0,'1','','',-1),
    (950000,'110445','Modern Hospital 46',0,0,0,1,0,0,'1','','',-1),
    (950000,'110446','Modern Hospital 47',0,0,0,1,0,0,'1','','',-1),
    (950000,'110447','Modern Hospital 48',0,0,0,1,0,0,'1','','',-1),
    (950000,'110448','Modern Hospital 49',0,0,0,1,0,0,'1','','',-1),
    (950000,'110449','Modern Hospital 50',0,0,0,1,0,0,'1','','',-1),
    (950000,'110450','Modern Hospital 51',0,0,0,1,0,0,'1','','',-1),
    (950000,'110451','Modern Hospital 52',0,0,0,1,0,0,'1','','',-1),
    (950000,'110452','Modern Hospital 53',0,0,0,1,0,0,'1','','',-1),
    (950000,'110453','Modern Hospital 54',0,0,0,1,0,0,'1','','',-1),
    (950000,'110454','Modern Hospital 55',0,0,0,1,0,0,'1','','',-1),
    (950000,'110455','Modern Hospital 56',0,0,0,1,0,0,'1','','',-1),
    (950000,'110456','Modern Hospital 57',0,0,0,1,0,0,'1','','',-1),
    (950000,'110457','Modern Hospital 58',0,0,0,1,0,0,'1','','',-1),
    (950000,'110458','Modern Hospital 59',0,0,0,1,0,0,'1','','',-1),
    (950000,'110459','Modern Hospital 60',0,0,0,1,0,0,'1','','',-1);
