-- PixelRP: the Asthorine set, in Builders > Customs > Asthorine.
--
-- The whole Asthorine set on ONE page under the existing Customs category,
-- beside Exterior Modern. Generated by docker/nitro/import-pack-tree.py.
--
-- The download is 65 bundles. 17 of them - the doors and windows - were
-- already imported by 94_CustomsFurni onto Medieval Doors, and are kept as
-- they are (their bundles, ids and names untouched): the epilogue only moves
-- their catalog rows here, so the set reads as one page. The other 48
-- are new.
--
-- The pack carries no names, so the new titles come from the classnames
-- ('Painting 11', 'Door 6 1x 2'); the 17 keep the names 94 gave them.
--
-- The rendering half is the .nitro bundles, the icons and the FurnitureData
-- entries under nitro/overrides/; the rows below are inert without them.
--
-- Everything is free - the catalog has been since 90_FreeCatalog.
--
-- Idempotent: fixed id ranges, cleared before insert. The 17 moved pieces are
-- addressed by id, and the sets under Customs are renumbered alphabetically,
-- so a re-run lands the same way.

SET @builders := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = -1 AND `caption` = 'Builders' LIMIT 1),
    912362);
SET @customs := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `id` = 944000 LIMIT 1),
    (SELECT `id` FROM `catalog_pages` WHERE `caption` = 'Customs' AND `parent_id` = @builders
        ORDER BY `id` LIMIT 1));

DELETE FROM `catalog_items` WHERE `item_id` BETWEEN 110600 AND 110647;
DELETE FROM `catalog_pages` WHERE `id` BETWEEN 951000 AND 951999;
DELETE FROM `furniture` WHERE `id` BETWEEN 110600 AND 110647;

INSERT INTO `catalog_pages`
    (`id`,`parent_id`,`caption`,`icon_image`,`min_rank`,`min_vip`,`order_num`,`page_link`,
     `page_layout`,`page_strings_1`,`page_strings_2`,`visible`,`enabled`)
VALUES
    (951000, @customs, 'Asthorine', 193, 2, 0, 1, '', 'default_3x3', '', '', b'1', b'1');


-- Furniture. id == sprite_id, the convention every custom line here follows;
-- interaction_modes_count is the bundle's own animation count.
INSERT INTO `furniture` (`id`,`item_name`,`public_name`,`type`,`width`,`length`,`stack_height`,`can_stack`,`can_sit`,`is_walkable`,`sprite_id`,`allow_recycle`,`allow_trade`,`allow_marketplace_sell`,`allow_gift`,`allow_inventory_stack`,`interaction_type`,`behaviour_data`,`interaction_modes_count`,`is_rare`) VALUES
    (110600,'asth_base1','Base 1','s',1,1,1.0,'1','0','0',110600,'0','1','0','1','1','default',0,1,'0'),
    (110601,'asth_base2','Base 2','s',1,1,1.0,'1','0','0',110601,'0','1','0','1','1','default',0,1,'0'),
    (110602,'asth_clock','Clock','s',1,1,1.0,'1','0','0',110602,'0','1','0','1','1','default',0,18,'0'),
    (110603,'asth_curtain','Curtain','s',1,1,1.0,'1','0','0',110603,'0','1','0','1','1','default',0,12,'0'),
    (110604,'asth_detail1','Detail 1','s',2,1,1.0,'1','0','0',110604,'0','1','0','1','1','default',0,3,'0'),
    (110605,'asth_detail2','Detail 2','s',2,1,1.0,'1','0','0',110605,'0','1','0','1','1','default',0,6,'0'),
    (110606,'asth_detail2_1x1','Detail 2 1x 1','s',1,1,1.0,'1','0','0',110606,'0','1','0','1','1','default',0,6,'0'),
    (110607,'asth_door10_1x2','Door 10 1x 2','s',2,1,1.0,'1','0','0',110607,'0','1','0','1','1','default',0,3,'0'),
    (110608,'asth_door3_1x2','Door 3 1x 2','s',2,1,1.0,'1','0','0',110608,'0','1','0','1','1','default',0,3,'0'),
    (110609,'asth_door4_1x2','Door 4 1x 2','s',2,1,1.0,'1','0','0',110609,'0','1','0','1','1','default',0,3,'0'),
    (110610,'asth_door5_1x2','Door 5 1x 2','s',2,1,1.0,'1','0','0',110610,'0','1','0','1','1','default',0,3,'0'),
    (110611,'asth_door6_1x2','Door 6 1x 2','s',2,1,1.0,'1','0','0',110611,'0','1','0','1','1','default',0,3,'0'),
    (110612,'asth_door7_1x1','Door 7 1x 1','s',1,1,1.0,'1','0','0',110612,'0','1','0','1','1','default',0,6,'0'),
    (110613,'asth_door7_1x2','Door 7 1x 2','s',2,1,1.0,'1','0','0',110613,'0','1','0','1','1','default',0,6,'0'),
    (110614,'asth_door9_1x1','Door 9 1x 1','s',1,1,1.0,'1','0','0',110614,'0','1','0','1','1','default',0,3,'0'),
    (110615,'asth_door9_1x2','Door 9 1x 2','s',2,1,1.0,'1','0','0',110615,'0','1','0','1','1','default',0,3,'0'),
    (110616,'asth_estatue','Estatue','s',1,1,1.0,'1','0','0',110616,'0','1','0','1','1','default',0,6,'0'),
    (110617,'asth_extra','Extra','s',1,1,1.0,'1','0','0',110617,'0','1','0','1','1','default',0,12,'0'),
    (110618,'asth_painting1','Painting 1','s',1,1,1.0,'1','0','0',110618,'0','1','0','1','1','default',0,3,'0'),
    (110619,'asth_painting10','Painting 10','s',3,1,1.0,'1','0','0',110619,'0','1','0','1','1','default',0,15,'0'),
    (110620,'asth_painting11','Painting 11','s',3,1,1.0,'1','0','0',110620,'0','1','0','1','1','default',0,15,'0'),
    (110621,'asth_painting12','Painting 12','s',3,1,1.0,'1','0','0',110621,'0','1','0','1','1','default',0,15,'0'),
    (110622,'asth_painting13','Painting 13','s',3,1,1.0,'1','0','0',110622,'0','1','0','1','1','default',0,15,'0'),
    (110623,'asth_painting2','Painting 2','s',1,1,1.0,'1','0','0',110623,'0','1','0','1','1','default',0,15,'0'),
    (110624,'asth_painting3','Painting 3','s',1,1,1.0,'1','0','0',110624,'0','1','0','1','1','default',0,15,'0'),
    (110625,'asth_painting4','Painting 4','s',1,1,1.0,'1','0','0',110625,'0','1','0','1','1','default',0,15,'0'),
    (110626,'asth_painting5','Painting 5','s',1,1,1.0,'1','0','0',110626,'0','1','0','1','1','default',0,15,'0'),
    (110627,'asth_painting6','Painting 6','s',1,1,1.0,'1','0','0',110627,'0','1','0','1','1','default',0,15,'0'),
    (110628,'asth_painting7','Painting 7','s',1,1,1.0,'1','0','0',110628,'0','1','0','1','1','default',0,15,'0'),
    (110629,'asth_painting8','Painting 8','s',3,1,1.0,'1','0','0',110629,'0','1','0','1','1','default',0,15,'0'),
    (110630,'asth_painting9','Painting 9','s',3,1,1.0,'1','0','0',110630,'0','1','0','1','1','default',0,15,'0'),
    (110631,'asth_pilar1','Pilar 1','s',1,1,1.0,'1','0','0',110631,'0','1','0','1','1','default',0,2,'0'),
    (110632,'asth_pilar2','Pilar 2','s',1,1,1.0,'1','0','0',110632,'0','1','0','1','1','default',0,2,'0'),
    (110633,'asth_tree','Tree','s',1,1,1.0,'1','0','0',110633,'0','1','0','1','1','default',0,4,'0'),
    (110634,'asth_versdoor1_1x2','Versdoor 1 1x 2','s',2,1,1.0,'1','0','0',110634,'0','1','0','1','1','default',0,6,'0'),
    (110635,'asth_versdoorwin1_1x1','Versdoorwin 1 1x 1','s',1,1,1.0,'1','0','0',110635,'0','1','0','1','1','default',0,18,'0'),
    (110636,'asth_verswind1_1x2','Verswind 1 1x 2','s',2,1,1.0,'1','0','0',110636,'0','1','0','1','1','default',0,12,'0'),
    (110637,'asth_window10_1x1','Window 10 1x 1','s',1,1,1.0,'1','0','0',110637,'0','1','0','1','1','default',0,3,'0'),
    (110638,'asth_window10_1x2','Window 10 1x 2','s',2,1,1.0,'1','0','0',110638,'0','1','0','1','1','default',0,3,'0'),
    (110639,'asth_window1_1x2','Window 1 1x 2','s',2,1,1.0,'1','0','0',110639,'0','1','0','1','1','default',0,9,'0'),
    (110640,'asth_window2_1x2','Window 2 1x 2','s',2,1,1.0,'1','0','0',110640,'0','1','0','1','1','default',0,9,'0'),
    (110641,'asth_window3_1x2','Window 3 1x 2','s',2,1,1.0,'1','0','0',110641,'0','1','0','1','1','default',0,12,'0'),
    (110642,'asth_window4_1x1','Window 4 1x 1','s',1,1,1.0,'1','0','0',110642,'0','1','0','1','1','default',0,9,'0'),
    (110643,'asth_window4_1x2','Window 4 1x 2','s',2,1,1.0,'1','0','0',110643,'0','1','0','1','1','default',0,9,'0'),
    (110644,'asth_window5_1x1','Window 5 1x 1','s',1,1,1.0,'1','0','0',110644,'0','1','0','1','1','default',0,12,'0'),
    (110645,'asth_window5_1x2','Window 5 1x 2','s',2,1,1.0,'1','0','0',110645,'0','1','0','1','1','default',0,12,'0'),
    (110646,'asth_window6_1x1','Window 6 1x 1','s',1,1,1.0,'1','0','0',110646,'0','1','0','1','1','default',0,12,'0'),
    (110647,'asth_window6_1x2','Window 6 1x 2','s',2,1,1.0,'1','0','0',110647,'0','1','0','1','1','default',0,12,'0');

INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`) VALUES
    (951000,'110600','Base 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110601','Base 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110602','Clock',0,0,0,1,0,0,'1','','',-1),
    (951000,'110603','Curtain',0,0,0,1,0,0,'1','','',-1),
    (951000,'110604','Detail 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110605','Detail 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110606','Detail 2 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110607','Door 10 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110608','Door 3 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110609','Door 4 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110610','Door 5 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110611','Door 6 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110612','Door 7 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110613','Door 7 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110614','Door 9 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110615','Door 9 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110616','Estatue',0,0,0,1,0,0,'1','','',-1),
    (951000,'110617','Extra',0,0,0,1,0,0,'1','','',-1),
    (951000,'110618','Painting 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110619','Painting 10',0,0,0,1,0,0,'1','','',-1),
    (951000,'110620','Painting 11',0,0,0,1,0,0,'1','','',-1),
    (951000,'110621','Painting 12',0,0,0,1,0,0,'1','','',-1),
    (951000,'110622','Painting 13',0,0,0,1,0,0,'1','','',-1),
    (951000,'110623','Painting 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110624','Painting 3',0,0,0,1,0,0,'1','','',-1),
    (951000,'110625','Painting 4',0,0,0,1,0,0,'1','','',-1),
    (951000,'110626','Painting 5',0,0,0,1,0,0,'1','','',-1),
    (951000,'110627','Painting 6',0,0,0,1,0,0,'1','','',-1),
    (951000,'110628','Painting 7',0,0,0,1,0,0,'1','','',-1),
    (951000,'110629','Painting 8',0,0,0,1,0,0,'1','','',-1),
    (951000,'110630','Painting 9',0,0,0,1,0,0,'1','','',-1),
    (951000,'110631','Pilar 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110632','Pilar 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110633','Tree',0,0,0,1,0,0,'1','','',-1),
    (951000,'110634','Versdoor 1 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110635','Versdoorwin 1 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110636','Verswind 1 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110637','Window 10 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110638','Window 10 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110639','Window 1 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110640','Window 2 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110641','Window 3 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110642','Window 4 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110643','Window 4 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110644','Window 5 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110645','Window 5 1x 2',0,0,0,1,0,0,'1','','',-1),
    (951000,'110646','Window 6 1x 1',0,0,0,1,0,0,'1','','',-1),
    (951000,'110647','Window 6 1x 2',0,0,0,1,0,0,'1','','',-1);

UPDATE `catalog_items` SET `page_id` = 951000
    WHERE `page_id` = 944065 AND `item_id` IN ('106095','106096','106097','106098','106099','106100','106101','106102','106103','106104','106105','106106','106107','106108','106109','106110','106111');
UPDATE `catalog_pages` SET `visible` = b'0', `enabled` = b'0'
    WHERE `id` = 944065 AND `caption` = 'Medieval Doors'
    AND NOT EXISTS (SELECT 1 FROM (SELECT `page_id` FROM `catalog_items`) AS `ci` WHERE `ci`.`page_id` = 944065);
SET @n := 0;
UPDATE `catalog_pages` SET `order_num` = (@n := @n + 1)
    WHERE `parent_id` = @customs
    ORDER BY `caption`;
