-- PixelRP: the Zara set, in Builders > Customs > Zara.
--
-- 6 clothing and rack pieces on ONE page under the existing Customs
-- category. Generated by docker/nitro/import-pack-tree.py.
--
-- The pack carries no names, so the titles come from the classnames
-- ('Clothing 1', 'Rack 2').
--
-- The rendering half is the .nitro bundles, the icons and the FurnitureData
-- entries under nitro/overrides/; the rows below are inert without them.
--
-- Everything is free - the catalog has been since 90_FreeCatalog.
--
-- Idempotent: fixed id ranges, cleared before insert. The sets under Customs are
-- renumbered alphabetically at the end, which lands the same way every run.

SET @builders := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = -1 AND `caption` = 'Builders' LIMIT 1),
    912362);
SET @customs := COALESCE(
    (SELECT `id` FROM `catalog_pages` WHERE `id` = 944000 LIMIT 1),
    (SELECT `id` FROM `catalog_pages` WHERE `caption` = 'Customs' AND `parent_id` = @builders
        ORDER BY `id` LIMIT 1));

DELETE FROM `catalog_items` WHERE `item_id` BETWEEN 110700 AND 110705;
DELETE FROM `catalog_pages` WHERE `id` BETWEEN 952000 AND 952999;
DELETE FROM `furniture` WHERE `id` BETWEEN 110700 AND 110705;

INSERT INTO `catalog_pages`
    (`id`,`parent_id`,`caption`,`icon_image`,`min_rank`,`min_vip`,`order_num`,`page_link`,
     `page_layout`,`page_strings_1`,`page_strings_2`,`visible`,`enabled`)
VALUES
    (952000, @customs, 'Zara', 193, 2, 0, 1, '', 'default_3x3', '', '', b'1', b'1');


-- Furniture. id == sprite_id, the convention every custom line here follows;
-- interaction_modes_count is the bundle's own animation count.
INSERT INTO `furniture` (`id`,`item_name`,`public_name`,`type`,`width`,`length`,`stack_height`,`can_stack`,`can_sit`,`is_walkable`,`sprite_id`,`allow_recycle`,`allow_trade`,`allow_marketplace_sell`,`allow_gift`,`allow_inventory_stack`,`interaction_type`,`behaviour_data`,`interaction_modes_count`,`is_rare`) VALUES
    (110700,'zara_clothing','Clothing','s',1,1,1.0,'1','0','0',110700,'0','1','0','1','1','default',0,1,'0'),
    (110701,'zara_clothing1','Clothing 1','s',1,1,1.0,'1','0','0',110701,'0','1','0','1','1','default',0,4,'0'),
    (110702,'zara_clothing3','Clothing 3','s',1,1,1.0,'1','0','0',110702,'0','1','0','1','1','default',0,2,'0'),
    (110703,'zara_rack1','Rack 1','s',1,1,1.0,'1','0','0',110703,'0','1','0','1','1','default',0,1,'0'),
    (110704,'zara_rack2','Rack 2','s',1,1,1.0,'1','0','0',110704,'0','1','0','1','1','default',0,1,'0'),
    (110705,'zara_rack3','Rack 3','s',1,1,1.0,'1','0','0',110705,'0','1','0','1','1','default',0,1,'0');

INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`) VALUES
    (952000,'110700','Clothing',0,0,0,1,0,0,'1','','',-1),
    (952000,'110701','Clothing 1',0,0,0,1,0,0,'1','','',-1),
    (952000,'110702','Clothing 3',0,0,0,1,0,0,'1','','',-1),
    (952000,'110703','Rack 1',0,0,0,1,0,0,'1','','',-1),
    (952000,'110704','Rack 2',0,0,0,1,0,0,'1','','',-1),
    (952000,'110705','Rack 3',0,0,0,1,0,0,'1','','',-1);

SET @n := 0;
UPDATE `catalog_pages` SET `order_num` = (@n := @n + 1)
    WHERE `parent_id` = @customs
    ORDER BY `caption`;
