-- PixelRP: furni Habbo has added since our library sync, and where it lives.
--
-- 27 items over 24 bundles. Generated by docker/nitro/import-habbo-sync.py -
-- see that file for how the set was diffed and what each rule files where.
-- Every field comes from Habbo's own furnidata (id, dimensions, cansiton,
-- canstandon, name) except stack height, which is read from the SWF's logic
-- XML because that is what the client renders against.
--
-- Clothing is excluded, as everywhere else: Habbo also added
-- clothing_nft26_nftwitchcape and hween_cloth_c26_checkerskirt, which this
-- shop does not sell.
--
-- Idempotent: fixed id ranges, cleared before insert. Targets are resolved by
-- caption because the catalog restore hands out fresh page ids each run.

DELETE FROM `catalog_items` WHERE `item_id` BETWEEN 100250 AND 100276;
DELETE FROM `catalog_pages` WHERE `id` BETWEEN 950000 AND 950099;
DELETE FROM `furniture` WHERE `id` BETWEEN 100250 AND 100276;

SET @staff   := (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = -1 AND `caption` = 'Staff' LIMIT 1);
SET @wired   := (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = @staff AND `caption` = 'Wired' LIMIT 1);
SET @waddons := (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = @wired AND `caption` = 'Add-Ons' LIMIT 1);
SET @wfx     := (SELECT `id` FROM `catalog_pages` WHERE `parent_id` = @wired AND `caption` = 'Effects' LIMIT 1);
SET @hol     := (SELECT p.`id` FROM `catalog_pages` p JOIN `catalog_pages` s ON s.`id` = p.`parent_id`
                 WHERE p.`caption` = 'Halloween' AND s.`caption` = 'Furni By Holiday' LIMIT 1);

-- Staff > NFT is new; Halloween > 2026 is the first item of its year.
INSERT INTO `catalog_pages`
    (`id`,`parent_id`,`caption`,`icon_image`,`min_rank`,`min_vip`,`order_num`,`page_link`,
     `page_layout`,`page_strings_1`,`page_strings_2`,`visible`,`enabled`)
SELECT 950000, @staff, 'NFT', 92, 5, 0, 20, '', 'default_3x3', '', '', b'1', b'1'
FROM DUAL WHERE @staff IS NOT NULL;
INSERT INTO `catalog_pages`
    (`id`,`parent_id`,`caption`,`icon_image`,`min_rank`,`min_vip`,`order_num`,`page_link`,
     `page_layout`,`page_strings_1`,`page_strings_2`,`visible`,`enabled`)
SELECT 950001, @hol, '2026', 34, 1, 0, 2026, '', 'default_3x3', '', '', b'1', b'1'
FROM DUAL WHERE @hol IS NOT NULL;
SET @nft  := 950000;
SET @h26  := 950001;

-- Furniture. sprite_id is the furnidata id, which is how the client resolves
-- the asset; furniture.id is ours and only the catalog refers to it.
INSERT INTO `furniture` (`id`,`item_name`,`public_name`,`type`,`width`,`length`,`stack_height`,`can_stack`,`can_sit`,`is_walkable`,`sprite_id`,`allow_recycle`,`allow_trade`,`allow_marketplace_sell`,`allow_gift`,`allow_inventory_stack`,`interaction_type`,`behaviour_data`,`interaction_modes_count`,`is_rare`) VALUES
    (100250,'hween26_nt_curseddragonlamp','Curseddragonlamp','s',1,1,1.0,'1','0','0',19191,'0','1','0','1','1','default',0,1,'0'),
    (100251,'nft_attic15_telescope','Cosmos Telescope','s',1,1,1.0,'1','0','0',19172,'0','1','0','1','1','default',0,1,'0'),
    (100252,'nft_bonusrare16_3*1','Ochre Bird of Paradise','s',1,1,1.0,'1','0','0',19173,'0','1','0','1','1','default',0,1,'0'),
    (100253,'nft_bonusrare16_3*2','Teal Bird of Paradise','s',1,1,1.0,'1','0','0',19174,'0','1','0','1','1','default',0,1,'0'),
    (100254,'nft_bonusrare16_3*3','Bonusrare16 3','s',1,1,1.0,'1','0','0',19175,'0','1','0','1','1','default',0,1,'0'),
    (100255,'nft_bonusrare16_3*4','Bonusrare16 3','s',1,1,1.0,'1','0','0',19176,'0','1','0','1','1','default',0,1,'0'),
    (100256,'nft_carnival15_hotair_brazil','Brazilian Hot Air Balloon','s',1,1,7.0,'1','1','0',19177,'0','1','0','1','1','default',0,1,'0'),
    (100257,'nft_fest_r19_gemowl','Gem-Studded Owl','s',1,1,1.0,'1','0','0',19178,'0','1','0','1','1','default',0,1,'0'),
    (100258,'nft_js_r16_heli','Deluxe HabboCopter','s',2,3,9.1,'1','1','0',19179,'0','1','0','1','1','default',0,1,'0'),
    (100259,'nft_js_r16_shark','Great White Shark','s',1,1,0.001,'1','0','1',19180,'0','1','0','1','1','default',0,1,'0'),
    (100260,'nft_plushie_r20_hammock','Cosy Hammock','s',1,1,2.3,'1','1','0',19181,'0','1','0','1','1','default',0,1,'0'),
    (100261,'nft_plushie_r20_picnictree','Ancient Oak Table','s',2,2,1.0,'1','0','0',19182,'0','1','0','1','1','default',0,1,'0'),
    (100262,'nft_rainyday_r19_fluffbun','Buffy','s',1,1,1.0,'1','0','0',19183,'0','1','0','1','1','default',0,1,'0'),
    (100263,'nft_rainyday_r19_rainbear','Little Raccoon','s',1,1,1.0,'1','0','0',19184,'0','1','0','1','1','default',0,1,'0'),
    (100264,'nft_rare_blackrosegold_scifiport','Rose Gold Laser Portal','s',1,1,0.0001,'1','0','1',19185,'0','1','0','1','1','default',0,1,'0'),
    (100265,'nft_rare_r20_balloonchair','Floating Chair','s',1,1,2.0,'1','1','0',19186,'0','1','0','1','1','default',0,1,'0'),
    (100266,'nft_rare_r20_wardrobe','Ornate Wardrobe','s',2,1,3.0,'1','0','0',19187,'0','1','0','1','1','default',0,1,'0'),
    (100267,'nft_school_gate','School Gates','s',3,1,0.0,'1','0','1',19188,'0','1','0','1','1','default',0,1,'0'),
    (100268,'nft_suncity_r19_glassfountain','Aqua Crystal Fountain','s',2,2,1.0,'1','0','0',19189,'0','1','0','1','1','default',0,1,'0'),
    (100269,'wf_fx_firegate','Firegate','s',1,1,0.0,'1','0','1',19194,'0','1','0','1','1','default',0,1,'0'),
    (100270,'wf_xtra_var_web_api','Variable Global Add-on: Web API','s',1,1,0.75,'1','0','1',19190,'0','1','0','1','1','default',0,1,'0'),
    (100271,'wf_xtra_varfx_boss','Varfx Boss','s',1,1,1.0,'1','0','1',19195,'0','1','0','1','1','default',0,1,'0'),
    (100272,'wf_xtra_varfx_hp','Varfx Hp','s',1,1,0.95,'1','0','1',19196,'0','1','0','1','1','default',0,1,'0'),
    (100273,'wf_xtra_varfx_levelling','Varfx Levelling','s',1,1,0.95,'1','0','1',19197,'0','1','0','1','1','default',0,1,'0'),
    (100274,'wf_xtra_varfx_number','Varfx Number','s',1,1,0.95,'1','0','1',19198,'0','1','0','1','1','default',0,1,'0'),
    (100275,'wf_xtra_varfx_prog','Varfx Prog','s',1,1,0.95,'1','0','1',19199,'0','1','0','1','1','default',0,1,'0'),
    (100276,'wf_xtra_varfx_status','Varfx Status','s',1,1,0.95,'1','0','1',19200,'0','1','0','1','1','default',0,1,'0');

-- halloween:2026 (1)
INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`)
SELECT @h26, '100250', 'Curseddragonlamp', 5, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @h26 IS NOT NULL;

-- nft (18)
INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`)
SELECT @nft, '100251', 'Cosmos Telescope', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100252', 'Ochre Bird of Paradise', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100253', 'Teal Bird of Paradise', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100254', 'Bonusrare16 3', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100255', 'Bonusrare16 3', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100256', 'Brazilian Hot Air Balloon', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100257', 'Gem-Studded Owl', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100258', 'Deluxe HabboCopter', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100259', 'Great White Shark', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100260', 'Cosy Hammock', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100261', 'Ancient Oak Table', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100262', 'Buffy', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100263', 'Little Raccoon', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100264', 'Rose Gold Laser Portal', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100265', 'Floating Chair', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100266', 'Ornate Wardrobe', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100267', 'School Gates', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL
UNION ALL
SELECT @nft, '100268', 'Aqua Crystal Fountain', 50000, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @nft IS NOT NULL;

-- wired_addons (7)
INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`)
SELECT @waddons, '100270', 'Variable Global Add-on: Web API', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @waddons IS NOT NULL
UNION ALL
SELECT @waddons, '100271', 'Varfx Boss', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @waddons IS NOT NULL
UNION ALL
SELECT @waddons, '100272', 'Varfx Hp', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @waddons IS NOT NULL
UNION ALL
SELECT @waddons, '100273', 'Varfx Levelling', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @waddons IS NOT NULL
UNION ALL
SELECT @waddons, '100274', 'Varfx Number', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @waddons IS NOT NULL
UNION ALL
SELECT @waddons, '100275', 'Varfx Prog', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @waddons IS NOT NULL
UNION ALL
SELECT @waddons, '100276', 'Varfx Status', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @waddons IS NOT NULL;

-- wired_effects (1)
INSERT INTO `catalog_items` (`page_id`,`item_id`,`catalog_name`,`cost_credits`,`cost_pixels`,`cost_diamonds`,`amount`,`limited_sells`,`limited_stack`,`offer_active`,`extradata`,`badge`,`offer_id`)
SELECT @wfx, '100269', 'Firegate', 3, 0, 0, 1, 0, 0, '1', '', '', -1 FROM DUAL WHERE @wfx IS NOT NULL;

