namespace Plus.HabboHotel.Items;

public enum InteractionType
{
    None,
    Gate,
    Postit,
    Moodlight,
    Trophy,
    Bed,
    Scoreboard,
    VendingMachine,
    Alert,
    OneWayGate,
    LoveShuffler,
    HabboWheel,
    Dice,
    Bottle,
    Hopper,
    Teleport,
    Pool,
    Roller,
    FootballGate,
    Pet,
    IceSkates,
    NormalSkates,
    Lowpool,
    Haloweenpool,
    Football,
    FootballGoalGreen,
    FootballGoalYellow,
    FootballGoalBlue,
    FootballGoalRed,
    Footballcountergreen,
    Footballcounteryellow,
    Footballcounterblue,
    Footballcounterred,
    Banzaigateblue,
    Banzaigatered,
    Banzaigateyellow,
    Banzaigategreen,
    Banzaifloor,
    Banzaiscoreblue,
    Banzaiscorered,
    Banzaiscoreyellow,
    Banzaiscoregreen,
    Banzaicounter,
    Banzaitele,
    Banzaipuck,
    Banzaipyramid,
    Freezetimer,
    Freezeexit,
    Freezeredcounter,
    Freezebluecounter,
    Freezeyellowcounter,
    Freezegreencounter,
    FreezeYellowGate,
    FreezeRedGate,
    FreezeGreenGate,
    FreezeBlueGate,
    FreezeTileBlock,
    FreezeTile,
    Jukebox,
    MusicDisc,
    PuzzleBox,
    Toner,


    PressurePad,

    WfFloorSwitch1,
    WfFloorSwitch2,

    Gift,
    Background,
    Mannequin,
    GateVip,
    GuildItem,
    GuildGate,
    GuildForum,

    Tent,
    TentSmall,
    BadgeDisplay,
    Stacktool,
    Television,

    WiredEffect,
    WiredTrigger,
    WiredCondition,

    Wallpaper,
    Floor,
    Landscape,

    Badge,
    CrackableEgg,
    Effect,
    Deal,
    Roomdeal,

    HorseSaddle1,
    HorseSaddle2,
    HorseHairstyle,
    HorseBodyDye,
    HorseHairDye,

    GnomeBox,
    Bot,
    PurchasableClothing,
    PetBreedingBox,
    Arrow,
    Lovelock,
    MonsterplantSeed,
    Cannon,
    Counter,
    CameraPicture,
    FxProvider,
    Exchange,
    DressingBooth,

    // pixelrp: the cash machine. A BEHAVIOUR rather than a classname check, so
    // a bank set can put it on a teller window or a wall panel without a code
    // change - the same route the jukebox took.
    Atm
}